# sample netlify.toml
[build]
command = "npm install"
  Functions = "functions" 
  publish = "public"
  NODE_ENV ="16.0.0"

[functions]
  node_bundler = "esbuild"




[[redirects]]
  from = "/*"
  to = "/404/404.html" 
  status = 404

